---
title: 613 Originals
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: ''
description: A Bootstrap 4 start up project for Jekyll and Github Pages
repository: nicolas-van/bootstrap-4-github-pages
plugins:
- jekyll-feed
- jekyll-sitemap
header_pages: 
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- update_boostrap.sh
